services:
  discord-bot:
    build: .
    container_name: discord-n8n-trigger
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    read_only: true
    tmpfs:
      - /tmp
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    extra_hosts:
      - "n8n.ahmedhanye.me:host-gateway"
